### ISSUE TITLE
Quick finder doesn't find polish characters

### ISSUE THREAD

**Issue by xrazdwa** [3nids/quickfinder#25]
if I'll try to find any words with polish characters (żźćńąśłóę) [in project search]  I have no results.  

Without polish characters, quickfinder works fine.

**Comment by 3nids** [comment]
I can't reproduce the bug.
I was able to find such characters in project.
Can you provide a demo project (project, layers, and qfts file)?

**Comment by xrazdwa** [comment]
ok
here is test project:
https://www.dropbox.com/s/0g03u15njfnpswe/test_pl.zip?dl=0

thing is

if search phrase does not contain polish characters then is no matter lower/upper case  - quickfinder find every letter, but if search phrase contain polish characters then lower/upper case is matter (you must write this letter exactly as it is).  

sorry for my english. i hope u understand me.
cheers.

**Comment by 3nids** [comment]
Hi,
I tried on Fedora and Windows 7, and could search for polish characters, and no matter the case of the searches string.
Sorry, I can't reproduce your problem!

**Comment by xrazdwa** [comment]
I made video:
https://www.youtube.com/watch?v=UV-_QmncvDQ
