### ISSUE TITLE
crash qgis 2.6.1

### ISSUE THREAD

**Issue by SEGAteam** [3nids/quickfinder#26]
bonjour a tous
Quand je veux selectionner l' ensemble d' objets d'une recherche , sur une couche de point et une une de polyligne, cela fait planter qgis.
J ai essayé sur 2 postes windows7.
Chaque résultat pris un par un fonctionne mais quand je choisi l'ensemble des resultats sur les 2 couches distinctes (même nom de sortie dans la boite de dialogue "search name")

Couche Ligne et polygone, fonctionne nikel pourtant!
ci joint le lien dump
https://drive.google.com/file/d/0B5P5IPMWPjZUdEdTTmQ3NDItcDA/view?usp=sharing

![im3](https://cloud.githubusercontent.com/assets/10676871/5883520/8851e16c-a353-11e4-886d-feb487d4368f.png)

![im1](https://cloud.githubusercontent.com/assets/10676871/5883500/40f7d39e-a353-11e4-9019-b74dd270c74b.png)

![im2](https://cloud.githubusercontent.com/assets/10676871/5883503/52cd907c-a353-11e4-8a98-8ab45eb888ee.png)

merci

**Comment by 3nids** [comment]
Bonjour,
Qu'entends-tu par sélectionner des objets de la recherche?
Sélection dans QGIS?

**Comment by SEGAteam** [comment]
merci
non je me suis mal exprimé, c'est faire une recherche sur un ensemble d' objets avec des geometries differentes (ex numero de dossier sur un reseau, et un poste élec)
mais j' ai trouvé la solution: c' est dans la priorité de la recherche CAD qu' il faut donner une priorité haute (ex:1) aux ponctuels et une, plus basse aux polylignes (ex:2)
dans ce cas, la recherche considere les lignes comme un ensemble de sommets ou noeuds, dans le cas contraire, qgis plante car la recherche ne peut differencier une polyligne, d' un ponctuel.

merci
