### ISSUE TITLE
Accessing plugin settings through QSettings

### ISSUE THREAD

**Issue by rbovard** [3nids/quickfinder#27]
Hi Denis,

Is there a way to access plugin settings through QSettings?

The goal is to deploy this plugin with some settings, especially `geomapfishUrl` and `geomapfishCrs`.

TIA

**Comment by 3nids** [comment]
Salut Rémi,
These settings are project related (QgsProject) and not global settings (QSettings).

See https://github.com/3nids/quickfinder/blob/master/core/mysettings.py

You can manually set them with `QgsProject.instance().writeEntry('quickfinder_plugin', 'geomapfishUrl','my_url')`

**Comment by rbovard** [comment]
Thanks for the quick answer and the explanation.

I understand how to set them with `writeEntry` but in this case, as you said, it's only project related. So if I open another project, those settings are gone.

Is not possible to add the possibility to store them in global settings? Still in the context of a global deploy.
