### ISSUE TITLE
plugin corruption cannot install/upgrade to rel.  3.2.6

### ISSUE THREAD

**Issue by marcobra** [3nids/quickfinder#34]
Hi the plugin

3.2.6 (in /home/ubuntu/.qgis2/python/plugins/quickfinder)

cannot upgrade or install itself due:

No module named qgsfieldexpressionwidget

With qgis:

Versione di QGIS	2.8.1-Wien	Revisione codice QGIS	exported
Compilato con Qt	4.8.6	Esecuzione con Qt	4.8.6
Compilato con GDAL/OGR	1.11.1	Esecuzione con GDAL/OGR	1.11.1
Compilato con GEOS	3.4.2-CAPI-1.8.2	Esecuzione con GEOS	3.4.2-CAPI-1.8.2 r3921
Versione client PostgreSQL	9.3.6	Versione SpatiaLite	4.1.1
Versione QWT	5.2.3	Versione PROJ.4	480
Versione QScintilla2	2.8.1

on 
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

**Comment by gilleschapron** [comment]
Hi everyone

I have the same problem with this update on Windows 7 with QGIS 2.8.1 64bits installed with OSGEO.

Thank you for this gread plugin.

Regards,

**Comment by 3nids** [comment]
this has been fixed.
thanks for reporting.
