### ISSUE TITLE
Panned to wrong position (Project search)

### ISSUE THREAD

**Issue by minorua** [3nids/quickfinder#37]
Seeing the plugin has become better and better, I was impressed. Search box in the tool bar and local database search are very convenient. Thank you very much!

I imported a set of point data of public facilities in Japan to a Quick Finder database and then did a search. I got a list of expected results, but when I clicked a result, map canvas panned to wrong position.

The CRS of the source layer is EPSG:4326 and the CRS of the QGIS project is EPSG:3099 (UTM zone 53N).

After a short investigation, I found FinderBox.resultFound() got a nonsense integer srid (e.g. 311763808) as the srid argument. The layer srid in the quickfinder_toc table of the database is correct (EPSG:4326), so the srid value got broken somewhere.

QGIS version 2.8.2, Plugin version 3.2.7

**Comment by Fromax** [comment]
I experienced the very same problem, but found out that it only occurs when using the *OpenLayers Plugin* at the same time (to display Google satellite imagery).
Disabling the *OpenLayers Plugin* usually cures the problem. Not sure what's going on...

QGIS 2.8.2, Quick Finder 3.2.7, OpenLayers Plugin 1.3.6, CRS: EPSG:25832 (ETRS89 / UTM zone 32N)

Thank you for making Quick Finder.

**Comment by 3nids** [comment]
This is fixed in release 3.2.8
Sorry for the delay!
