### ISSUE TITLE
another bug with polish characters

### ISSUE THREAD

**Issue by xrazdwa** [3nids/quickfinder#38]
I updated quickfinder to 3.2.10 and now ...
When first letter of the search word is polish character then ...not found 
in other case qf work perfectly.

video:
https://www.youtube.com/watch?v=mn1HbaY6Xdo

**Comment by 3nids** [comment]
this will require to create a new FTS file, sorry.

**Comment by xrazdwa** [comment]
ehhhmmm..

video:
https://www.youtube.com/watch?v=ELVEgXtbcIA

**Comment by 3nids** [comment]
ok, this is a bug related to the Osgeo4W packages.
Please update your packages (SQLite should now be 3.7.17-2), and it should be ok!

**Comment by 3nids** [comment]
for reference http://lists.osgeo.org/pipermail/osgeo4w-dev/2015-July/002947.html
