### ISSUE TITLE
Qgis 2.10.0 sqlite problem

### ISSUE THREAD

**Issue by stevenkatona** [3nids/quickfinder#39]
I have installed qgis (a vanilla install) using osgeo4w installer. When i run the quick finder plugin and create a new project database, the plugin fails to create the quickfinder_data table during "createFTSfile" (projectfinder.py). 

How can i check/configure qgis(and the sqlite it uses) so that the FTS ext is available. 
Looking at the packages dir for osgeo4w, the version of sqlite is 3.7.17. By default, i would have expected FTS to be included in this version of sqlite.

**Comment by stevenkatona** [comment]
I have just installed the development build for qgis (osgeo4w) 2.11.0-Master. The problem has been resolved. The plugin works flawlessly.

**Comment by 3nids** [comment]
Hi,
This error is not due do the presence of FTS in SQLite (it is included) but an additional encoding. It has been added recently to OSGeo4W packages. So, even with 2.8 or 2.10, if you update the SQLite package in the OSGeo4W installer, it works.

Although, I tried to handle this error, but apparently it doesn't work as expected. I'll try to see if I can fix this.

Thanks for reporting.
