### ISSUE TITLE
Please move it under the appropriate menu

### ISSUE THREAD

**Issue by pcav** [3nids/quickfinder#41]
Presumably under Web.
Merci.

**Comment by 3nids** [comment]
Well, it's not really related to the web as you can also have local searches.

**Comment by pcav** [comment]
Right. WHat about vector then?

**Comment by rbovard** [comment]
Neither, it's not vector related... For me it's most a generic tool.

**Comment by pcav** [comment]
ok, accepted.
Thanks.
