### ISSUE TITLE
Store optionnaly geometry, bbox or field value

### ISSUE THREAD

**Issue by mdouchin** [3nids/quickfinder#51]
When dealing with large datasets, it could be handy to have an option letting the user decide which data to store:
- geometry in WKB (as default now)
- geometry in GeoJSON ( for small datasets, it could be handy to use the database outside QGIS )
- bbox as a string 'Xmin,Ymin,Xmax,Ymax' -> the plugin would show a rectangle around the feature instead of its geometry (much smaller than storing full wkb geom ). Another app could use the generated database and get the bbox to display.
- primary key of the layer (or another field) -> the plugin (or other app outside QGIS) would be able to query the feature (of course knowledge of the layer structure is necessary here).

This could be an option put just under the Field/Expression input when adding a new "layer search".
We could have the type chosen stored in the metadata for the layer, and the plugin would act depending on it.

**Comment by mdouchin** [comment]
I could propose a PR if there is a consensus around this idea

**Comment by 3nids** [comment]
This sounds like a good option!
Feel free to PR!

**Comment by mdouchin** [comment]
@3nids What is the branch compatible with QGIS 2.*
I have just read the metadata file, and master is obviously made for upcoming QGIS 3

**Comment by 3nids** [comment]
my first intention was not to release any new 2.x version.
I just made a new branch master_2.

**Comment by mdouchin** [comment]
Ok, thanks !

**Comment by mdouchin** [comment]
pr #52 proposed, need some testing ( just wrote it without testing in QGIS, waiting to build V3 )

**Comment by mdouchin** [comment]
pr #53 for master_2 branch (tested in QGIS 2.16)
