### ISSUE TITLE
[OSM Results] Conflict with layers

### ISSUE THREAD

**Issue by ponceta** [3nids/quickfinder#56]
I do no longer receive OSM nominatim entries?

Am I the only one?

![image](https://cloud.githubusercontent.com/assets/8614223/20053280/227c0682-a4d8-11e6-9edb-54f85e527eaa.png)

![image](https://cloud.githubusercontent.com/assets/8614223/20053295/3333c690-a4d8-11e6-98e4-403b6ab012cb.png)

QGIS 2.14.8 Quickfinder 3.3.0

**Comment by rbovard** [comment]
Works fine here:

![image](https://cloud.githubusercontent.com/assets/4549666/20053567/74f6ffb0-a4d9-11e6-973e-cfd1af044325.png)

**Comment by ponceta** [comment]
Works fine via Osgeo4w installed QGIS 2.18.0

**Comment by 3nids** [comment]
There used to be a problem with the standalone installer of QGS which used a version of sqlite without unicode61. I thought this problem was handled now (i.e QuickFinder detects if unicode61 is available or not).

Is the problem still here?

**Comment by ponceta** [comment]
I found it, by me it's not related on QGIS versions but on project layers.

If I add a layer, I get conflicts and no results for osm.

If I have no layer quickfinder works fine.

![image](https://cloud.githubusercontent.com/assets/8614223/20054965/59a4cfde-a4df-11e6-837a-1e0045419602.png)

![image](https://cloud.githubusercontent.com/assets/8614223/20054976/61af2e86-a4df-11e6-9d14-37c4b29d9045.png)

**Comment by jtrebilcock** [comment]
I am having the same problem. Removing project searches does not fix the problem for me
