### ISSUE TITLE
quickfinder Bug 2.18.12 

### ISSUE THREAD

**Issue by mattylangz** [3nids/quickfinder#67]
Had a bug with the Quickfinder tried to find a city and state but it is stuck with loading and an error pops up saying QuickFinder: The service did not reply properly. Please check service definition. 
Tried Uninstalling/Reinstalling plugin. Hope this has a fix. 

![quickfinder bug1](https://user-images.githubusercontent.com/25852856/39949880-955448b6-5532-11e8-80db-0590463db88a.JPG)
![searchbar_stuck](https://user-images.githubusercontent.com/25852856/39949881-956d30ec-5532-11e8-9a3b-658e9e7187f6.JPG)

**Comment by TotalNoobOnGIS** [comment]
Same thing happened to me. 
QuickFinder is/was extremely handy

**Comment by mattylangz** [comment]
thanks. I have found a workaround for it but it all seems to work now. Redownloaded Quickfinder and it is operational again. 

Closing this out
